### ISSUE TITLE
Problem report server

### ISSUE THREAD

**Issue by juliensz** [smashtestio/smashtest#29]
Hi,

We have a problem with Report server:

I run this command : 
`smashtest --test-server=http://localhost:5959/wd/hub --report-domain=localhost:443`

but in my nav (chrome Version 76.0.3809.132 64 bits) i have this message 

> Upgrade Required

and in my console :
![2019-08-28_14h38_36](https://user-images.githubusercontent.com/49635283/63856282-82082400-c9a1-11e9-9717-44848484c56d.png)

The error is 426 : change protocol for TLS.

Thannk's

**Comment by juliensz** [comment]
Hi,

I have this error on Firefox : 

> The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

I leave in Frrance, is not a problem with UTF-8 ?

Thank's

**Comment by vptes1** [comment]
By "nav" do you mean your browser?
Also, what version of Smashtest are you running? We had a report encoding bug that was fixed about a month ago.

**Comment by vptes1** [comment]
Try upgrading to version `1.2.6`. We put an additional charset meta tag into the report. This should solve your problem.

**Comment by juliensz** [comment]
Hi,

I update my version :
![image](https://user-images.githubusercontent.com/49635283/64151267-47333f80-ce2a-11e9-9f32-f0dc2fe3e5a9.png)

But I still have the same problem that requires me to upgrade, with the error 426.

**Comment by juliensz** [comment]
Hi,

i update my version, but i have a same problem with my browser : error 426.

if there is need for more information to detect the problem I can provide it

Thank's

**Comment by vptes1** [comment]
Yes, please provide any additional information you can, including screenshots of the "character encoding" error.

**Comment by juliensz** [comment]
I make a vidéo in the ZIP file for show you my problem.
[Problem loading page - Mozilla Firefox 2019-09-03 15-19-25.zip](https://github.com/smashtestio/smashtest/files/3569611/Problem.loading.page.-.Mozilla.Firefox.2019-09-03.15-19-25.zip)

**Comment by vptes1** [comment]
I'm having trouble unzipping that file. Can you try uploading the video directly?

**Comment by juliensz** [comment]
this is my vidéo : https://youtu.be/uFGumvpTyjM

**Comment by vptes1** [comment]
In the video you try to open `localhost:8080`. What is at that location? The Smashtest report is a file whose path is outputted to the console.

**Comment by juliensz** [comment]
i use --report-domain=localhost:8080 like on doc :

>--report-domain=[domain or domain:port]
Domain where the report server should run. This is where the report page gets its live updates.
Port indicates what port smashtest should run on. If omitted, an open port will be chosen, starting with port 9000.
Domain indicates the domain of the machine you're running smashtest on. When this option is omitted, localhost is chosen by default. Choose a domain other than localhost for when you're running tests in CI and want people to hit the report externally.

**Comment by vptes1** [comment]
You shouldn't open the report-domain in your browser. Instead, look up the report path in the console output and open that. The report-domain sets the location of the report server, which the report html page connects to via websocket in the background.

**Comment by juliensz** [comment]
Ok so there is no url in real time?
To be able to monitor in real time and manage the logging of tests?

**Comment by vptes1** [comment]
The report file (from the path in the console) updates itself in real time as the tests run.

**Comment by juliensz** [comment]
Ok thank you! Nnow I have to find a way that the .html file does not fade each test run (I think about a backup on an AWS and call it on a web interface)

**Comment by vptes1** [comment]
If you want to keep your old report.html files, I recommend copying them to a different location or renaming them, after each test run.

If you have any more questions, the Smashtest Gitter is a great place to ask the community: https://gitter.im/smashtestio/community
